name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Set single SDK path
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Accept licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :module:assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: module
          path: "**/*.zip"
